#!/usr/bin/env ruby
# encoding: utf-8
require 'settingslogic'
require 'active_support/core_ext/string'
require 'plist'

bundle_display_hash = {
  yonghui: '永辉生意人',
  shengyiplus: '生意+',
  qiyoutong: '企邮通'
}
bundle_display_names = bundle_display_hash.keys.map(&:to_s)

current_app = ARGV.shift || 'null' #File.read('.current-app').strip.freeze
unless bundle_display_names.include?(current_app)
  puts %(appname should in #{bundle_display_names}, but #{current_app})
  exit
end

`echo '#{current_app}' > .current-app`
puts %(#{'-' * 25}\ncurrent app: #{current_app}\n#{'-' * 25}\n\n)

NAME_SPACE = current_app # TODO: namespace(variable_instance)
class Settings < Settingslogic
  source 'config/config.yaml'
  namespace NAME_SPACE
end

#
# reset bundle display name
#
plist_path = "YH-IOS/Info.plist"
plist_hash = Plist::parse_xml(plist_path)
plist_hash['CFBundleDisplayName'] = bundle_display_hash[current_app.to_sym]
plist_hash['CFBundleName'] = bundle_display_hash[current_app.to_sym]
File.open(plist_path, 'w:utf-8') { |file| file.puts(plist_hash.to_plist) }
puts %(bundle display name: #{bundle_display_hash[current_app.to_sym]})

#
# reset assets.xcassets
#

`rm -fr YH-IOS/Assets.xcassets/AppIcon.appiconset && cp -rf config/Assets.xcassets/AppIcon-#{current_app}.appiconset YH-IOS/Assets.xcassets/AppIcon.appiconset`
`rm -fr YH-IOS/Assets.xcassets/AppIcon.imageset && cp -rf config/Assets.xcassets/AppIcon-#{current_app}.imageset YH-IOS/Assets.xcassets/AppIcon.imageset`
`rm -fr YH-IOS/Assets.xcassets/Nav-Banner.imageset && cp -rf config/Assets.xcassets/Nav-Banner-#{current_app}.imageset YH-IOS/Assets.xcassets/Nav-Banner.imageset`
`rm -fr YH-IOS/Assets.xcassets/background.imageset && cp -rf config/Assets.xcassets/background-#{current_app}.imageset YH-IOS/Assets.xcassets/background.imageset`

#
# rewrite private setting
# 
constant_path = 'YH-IOS/Shared/constant_private.h'
File.open(constant_path, 'w:utf-8') do |file|
  file.puts <<-EOF.strip_heredoc
  //  constant_private.h
  //  
  //  `bundle install`
  //  `bundle exec ruby app_kepper.rb`
  //
  //  Created by lijunjie on 16/04/08.
  //  Copyright © 2016年 com.intfocus. All rights reserved.
  //

  // current app: [#{current_app}]
  // automatic generated by app_keeper.rb
  #ifndef constant_private_h
  #define constant_private_h

  #define BASE_URL @"#{Settings.server}"
  #define BASE_URL1 @"http://localhost:4567"
  #define PGYER_APP_ID @"#{Settings.pgyer.ios}"
  #define UMENG_APP_ID @"#{Settings.umeng.ios}"

  #endif /* constant_private_h */
  EOF
end
puts %(rewrite private setting done.)

