#!/usr/bin/env ruby
# encoding: utf-8
require 'settingslogic'
require 'active_support/core_ext/string'
require 'plist'

def file_path(file_name)
  %(YH-IOS/Shared/#{file_name})
end

current_app = ARGV.shift || 'null' #File.read('.current-app').strip.freeze
unless %w(yonghui shengyiplus).include?(current_app)
  puts %(appname should in {yonghui|shengyiplus}, but #{current_app})
  exit
end

`echo '#{current_app}' > .current-app`
puts %(#{'-' * 25}\ncurrent app: #{current_app}\n#{'-' * 25}\n\n)

NAME_SPACE = current_app # TODO: namespace(variable_instance)
class Settings < Settingslogic
  source file_path('config.yaml')
  namespace NAME_SPACE
end

#
# reset bundle display name
#
plist_path = "YH-IOS/Info.plist"
bundle_display_names = {
  yonghui: '永辉生意人',
  shengyiplus: '生意+'
}
plist_hash = Plist::parse_xml(plist_path)
plist_hash['CFBundleDisplayName'] = bundle_display_names[current_app.to_sym]
plist_hash['CFBundleName'] = bundle_display_names[current_app.to_sym]
File.open(plist_path, 'w:utf-8') { |file| file.puts(plist_hash.to_plist) }
puts %(bundle display name: #{bundle_display_names[current_app.to_sym]})

#
# rewrite private setting
# 
constant_path = file_path('constant_private.h')
File.open(constant_path, 'w:utf-8') do |file|
  file.puts <<-EOF.strip_heredoc
  //  constant_private.h
  //  
  //  `bundle install`
  //  `bundle exec ruby app_kepper.rb`
  //
  //  Created by lijunjie on 16/04/08.
  //  Copyright © 2016年 com.intfocus. All rights reserved.
  //

  // current app: [#{current_app}]
  // automatic generated by app_keeper.rb
  #ifndef constant_private_h
  #define constant_private_h

  #define BASE_URL @"#{Settings.server}"
  #define PGYER_APP_ID @"#{Settings.pgyer_app_id}"
  #define UMENG_APP_ID @"#{Settings.umeng_app_id}"

  #endif /* constant_private_h */
  EOF
end
puts %(rewrite private setting done.)

