#!/usr/bin/env ruby
# encoding: utf-8
require 'settingslogic'
require 'active_support/core_ext/string'

def file_path(file_name)
  %(YH-IOS/Shared/#{file_name})
end

CURRENT_APP = File.read('.current-app').strip.freeze
unless %w(yonghui shengyiplus).include?(CURRENT_APP)
  puts %(#{CURRENT_APP} not in [yonghui, shengyiplus])
  exit
end

class Settings < Settingslogic
  source file_path('config.yaml')
  namespace CURRENT_APP
end


constant_path = file_path('constant_private.h')
File.open(constant_path, 'w:utf-8') do |file|
  file.puts <<-EOF.strip_heredoc
  //  constant_private.h
  //  
  //  `bundle install`
  //  `bundle exec ruby app_kepper.rb`
  //
  //  Created by lijunjie on 16/04/08.
  //  Copyright © 2016年 com.intfocus. All rights reserved.
  //

  // current app: [#{CURRENT_APP}]
  // automatic generated by app_keeper.rb
  #ifndef constant_private_h
  #define constant_private_h

  #define BASE_URL @"#{Settings.server}"
  #define PGYER_APP_ID @"#{Settings.pgyer_app_id}"
  #define UMENG_APP_ID @"#{Settings.umeng_app_id}"

  #endif /* constant_private_h */
  EOF
end

