//  PrivateConstants.h
//  
//  `bundle install`
//  `./appkeeper.sh yonghuitest`
//
//  Created by lijunjie on 16/04/08.
//  Copyright © 2016年 com.intfocus. All rights reserved.
//

// current app: [yonghuitest]
// automatic generated by app_keeper.rb
#ifndef PrivateConstants_h
#define PrivateConstants_h

#define kAppCode          @"yonghuitest"
#define kBaseUrl          @"http://yonghui-test.idata.mobi"
#define kBaseUrl1         @"http://localhost:4567"

#define kInitPassword     @"123456"
#define kLoginSlogan      @"融合共享，成于至善"

#define kPgyerAppId       @"1d835e3e87539d37790403d1e5f26ef6"
#define kPgyerUrl         @"http://www.pgyer.com/yh-test-i"

#define kUMAppId          @"57b522fee0f55a7ba8001606"
#define kWXAppId          @"wxc48d00458356ccb6"
#define kWXAppSecret      @"2ee0c11d37b992dc882c7fe967469fa7"

#define kDashboardAd      NO

#define kDropMenuScan     YES
#define kDropMenuVoice    YES
#define kDropMenuSearch   YES
#define kDropMenuUserInfo YES

#define kTabBar           YES
#define kTabBarKPI        YES
#define kTabBarAnalyse    YES
#define kTabBarApp        YES
#define kTabBarMessage    YES

#define kSubjectComment   YES
#define kSubjectShare     YES

#endif /* PrivateConstants_h */
