//  constant_private.h
//  
//  `bundle install`
//  `bundle exec ruby app_kepper.rb`
//
//  Created by lijunjie on 16/04/08.
//  Copyright © 2016年 com.intfocus. All rights reserved.
//

// current app: [yonghui]
// automatic generated by app_keeper.rb

#import "constant_private.h"

NSString *const kHost = @"http://yonghui.idata.mobi";
NSString *const kPGYAppId = @"7586e8c77ceadd3240c5e243e9d0c391";
NSString *const kPGYInstallUrl = @"http://www.pgyer.com/yh-i";
NSString *const kUMAppId = @"56f9ebad67e58eb4990012c8";
NSString *const kUMWXAppId = @"wx9173274e2ea0d365";
NSString *const kUMWXAppSecret = @"22a92f9b55da6357e02e25f069ad7883";
BOOL const kDashboardTabBarDisplayKPI = YES;
BOOL const kDashboardTabBarDisplayAnalyse = YES;
BOOL const kDashboardTabBarDisplayApp = YES;
BOOL const kDashboardTabBarDisplayMessage = YES;
BOOL const kDashboardDisplayScanCode = YES;
BOOL const kSubjectDisplayComment = YES;

