//  PrivateConstants.h
//  
//  `bundle install`
//  `./appkeeper.sh yonghuitest`
//
//  Created by lijunjie on 16/04/08.
//  Copyright © 2016年 com.intfocus. All rights reserved.
//

// current app: [yonghuitest]
// automatic generated by app_keeper.rb
#ifndef PrivateConstants_h
#define PrivateConstants_h

#define kBaseUrl     @"http://yonghui-test.idata.mobi"
#define kBaseUrl1    @"http://localhost:4567"

#define kPgyerAppId  @"1d835e3e87539d37790403d1e5f26ef6"
#define kPgyerUrl    @"http://www.pgyer.com/yh-test-i"

#define kUMAppId     @"56f9ebad67e58eb4990012c8"
#define kWXAppId     @"wx9173274e2ea0d365"
#define kWXAppSecret @"22a92f9b55da6357e02e25f069ad7883"

#define kDashboardTabBarDisplay        YES
#define kDashboardTabBarDisplayKPI     YES
#define kDashboardTabBarDisplayAnalyse YES
#define kDashboardTabBarDisplayApp     YES
#define kDashboardTabBarDisplayMessage YES
#define kDashboardDisplayScanCode      YES
#define kSubjectDisplayComment         YES
#define kSubjectDisplayShare           YES

#endif /* PrivateConstants_h */
